### PR TITLE
Remove extra "Ruleset" from generated class names in ruleset-empty

### LINKED ISSUE #17: Generated class names are too verbose
When generating an empty ruleset with the name "Xxx", the classes it generates are e.g. `XxxRulesetAutoGenerator` and `XxxRulesetRuleset`. It would be better of the "Ruleset" was dropped so they would become `XxxAutoGenerator` and `XxxRuleset`.

### PR DESCRIPTION
**Pull request by holly-hacker**
Untested, but should work.

Closes #17

### CODE REVIEW

**Review by frenzibyte — DISMISSED** [review]

**Comment by peppy** [comment]
i think for conformity this should just be renamed to `Empty`. this can be done by installing the template (using this PR) and using it to generate a new one without the ruleset prefix.

Here's the rough required command to do so (and may help you with testing your PRs too):

```shell
dotnet pack;
dotnet new --install bin/Debug/ppy.Osu.Game.Templates.1.0.0.nupkg 
```

**Comment by frenzibyte** [comment]
> i think for conformity this should just be renamed to `Empty`.

Would fuck up some functions like `Enumerable.Empty()` -> `Enumerable.MyRuleset()` though which we discussed and agreed to rename to something other than that. I was fine with `EmptyNonScrolling` but seem so long with other files like `DrawableXxxHitObject` -> `DrawableEmptyNonScrollingHitObject`...

**Comment by holly-hacker** [comment]
Seeing as how `ruleset-scrolling-empty` is named `EmptyScrolling`, I'll remove `Ruleset` from the name in the project so it becomes `EmptyFreeform` everywhere. That shouldn't give conflicts.

**Comment by holly-hacker** [comment]
Renamed the ruleset from EmptyFreeformRuleset to EmptyFreeform, tested and works as intended. I also added a .gitattributes files to stop Rider from changing the line endings.

**Review by peppy — APPROVED** [review]

**Pull request merged**
